export default {
    projects: [
        {
            id: '6',
            imageSrc: 'images/burger.svg',
            imageAlt: 'double decker burger icon',
            background: '#45bce5',
            textColor: '#f8f7f7',
            title: 'Eat Da Burger',
            path: '/eat-da-burger',
            description: 'Eat Da Burger is a web application deployed with Heroku. On home page load, the user is presented with any existing burgers in the MySQL database, non-devoured burgers in the \'Ready to Eat\' section and devoured burgers in the \'Devoured\' section. There is also a form to allow them to input the name of new burgers they\'d like to eat. Once they hit submit, the new burger is added to the MySQL database as ready to eat and the page is reloaded so the burger is displayed in the appropriate section with a \'Devour It!\' button. If the user clicks this button the devoured state for that burger is updated in the MySQL database and the page is reloaded showing the burger moved to the \'Devoured\' section of the page.',
            organization: 'This application is organized using the Model-View-Controller (MVC) design pattern. An Object Relational Mapper (ORM) is defined with functions to handle the MySQL queries and the model further defines those functions specific to the Eat Da Burger application. The routing is defined in the controller and the functions are called as appropriate, once database data is gathered or altered, the view updates from the Handlebars template using a page reload.',
            technologies: 'HTML, Handlebars, CSS, JavaScript, jQuery, MySQL, Node.js, Express, Heroku',
            npmPackages: 'express, express-handlebars, mysql',
            role: 'Sole developer with functionality requirements provided by UW Coding Bootcamp/Trilogy Education Services. Responsible for website design and creation of custom graphics.',
            githubLink: 'https://github.com/lexi-winstanley/BurgerLog',
            projectLink: 'https://nameless-taiga-35229.herokuapp.com/',
            projectImageSrc: '',
            projectImageAlt: ''
        },
        {
            id: '8',
            imageSrc: 'images/pawPrint.svg',
            imageAlt: 'dog paw print icon',
            background: '#b5ca30',
            textColor: '#0F0F0D',
            title: 'Dog Breed Guessing Game',
            path: '/eat-da-burger',
            description: 'Eat Da Burger is a web application deployed with Heroku. On home page load, the user is presented with any existing burgers in the MySQL database, non-devoured burgers in the \'Ready to Eat\' section and devoured burgers in the \'Devoured\' section. There is also a form to allow them to input the name of new burgers they\'d like to eat. Once they hit submit, the new burger is added to the MySQL database as ready to eat and the page is reloaded so the burger is displayed in the appropriate section with a \'Devour It!\' button. If the user clicks this button the devoured state for that burger is updated in the MySQL database and the page is reloaded showing the burger moved to the \'Devoured\' section of the page.',
            organization: 'This application is organized using the Model-View-Controller (MVC) design pattern. An Object Relational Mapper (ORM) is defined with functions to handle the MySQL queries and the model further defines those functions specific to the Eat Da Burger application. The routing is defined in the controller and the functions are called as appropriate, once database data is gathered or altered, the view updates from the Handlebars template using a page reload.',
            technologies: 'HTML, Handlebars, CSS, JavaScript, jQuery, MySQL, Node.js, Express, Heroku',
            npmPackages: 'express, express-handlebars, mysql',
            role: 'Sole developer with functionality requirements provided by UW Coding Bootcamp/Trilogy Education Services. Responsible for website design and creation of custom graphics.',
            githubLink: 'https://github.com/lexi-winstanley/BurgerLog',
            projectLink: 'https://nameless-taiga-35229.herokuapp.com/',
            projectImageSrc: '',
            projectImageAlt: ''
        },
        {
            id: '9',
            imageSrc: 'images/packIt.svg',
            imageAlt: '',
            background: '#680a4d',
            textColor: '#f8f7f7',
            title: 'Pack It!',
            path: '/eat-da-burger',
            description: 'Eat Da Burger is a web application deployed with Heroku. On home page load, the user is presented with any existing burgers in the MySQL database, non-devoured burgers in the \'Ready to Eat\' section and devoured burgers in the \'Devoured\' section. There is also a form to allow them to input the name of new burgers they\'d like to eat. Once they hit submit, the new burger is added to the MySQL database as ready to eat and the page is reloaded so the burger is displayed in the appropriate section with a \'Devour It!\' button. If the user clicks this button the devoured state for that burger is updated in the MySQL database and the page is reloaded showing the burger moved to the \'Devoured\' section of the page.',
            organization: 'This application is organized using the Model-View-Controller (MVC) design pattern. An Object Relational Mapper (ORM) is defined with functions to handle the MySQL queries and the model further defines those functions specific to the Eat Da Burger application. The routing is defined in the controller and the functions are called as appropriate, once database data is gathered or altered, the view updates from the Handlebars template using a page reload.',
            technologies: 'HTML, Handlebars, CSS, JavaScript, jQuery, MySQL, Node.js, Express, Heroku',
            npmPackages: 'express, express-handlebars, mysql',
            role: 'Sole developer with functionality requirements provided by UW Coding Bootcamp/Trilogy Education Services. Responsible for website design and creation of custom graphics.',
            githubLink: 'https://github.com/lexi-winstanley/BurgerLog',
            projectLink: 'https://nameless-taiga-35229.herokuapp.com/',
            projectImageSrc: '',
            projectImageAlt: ''
        },
        {
            id: '10',
            imageSrc: 'images/gifGenerator.svg',
            imageAlt: 'gif generator icon',
            background: '#041232',
            textColor: '#f8f7f7',
            title: 'GIF Generator',
            path: '/eat-da-burger',
            description: 'Eat Da Burger is a web application deployed with Heroku. On home page load, the user is presented with any existing burgers in the MySQL database, non-devoured burgers in the \'Ready to Eat\' section and devoured burgers in the \'Devoured\' section. There is also a form to allow them to input the name of new burgers they\'d like to eat. Once they hit submit, the new burger is added to the MySQL database as ready to eat and the page is reloaded so the burger is displayed in the appropriate section with a \'Devour It!\' button. If the user clicks this button the devoured state for that burger is updated in the MySQL database and the page is reloaded showing the burger moved to the \'Devoured\' section of the page.',
            organization: 'This application is organized using the Model-View-Controller (MVC) design pattern. An Object Relational Mapper (ORM) is defined with functions to handle the MySQL queries and the model further defines those functions specific to the Eat Da Burger application. The routing is defined in the controller and the functions are called as appropriate, once database data is gathered or altered, the view updates from the Handlebars template using a page reload.',
            technologies: 'HTML, Handlebars, CSS, JavaScript, jQuery, MySQL, Node.js, Express, Heroku',
            npmPackages: 'express, express-handlebars, mysql',
            role: 'Sole developer with functionality requirements provided by UW Coding Bootcamp/Trilogy Education Services. Responsible for website design and creation of custom graphics.',
            githubLink: 'https://github.com/lexi-winstanley/BurgerLog',
            projectLink: 'https://nameless-taiga-35229.herokuapp.com/',
            projectImageSrc: '',
            projectImageAlt: ''
        },
        {
            id: '12',
            imageSrc: 'images/urbanPrairieWheat.svg',
            imageAlt: '',
            background: '#0072bb',
            textColor: '#f8f7f7',
            title: 'Urban Prairie Homes',
            path: '/eat-da-burger',
            description: 'Eat Da Burger is a web application deployed with Heroku. On home page load, the user is presented with any existing burgers in the MySQL database, non-devoured burgers in the \'Ready to Eat\' section and devoured burgers in the \'Devoured\' section. There is also a form to allow them to input the name of new burgers they\'d like to eat. Once they hit submit, the new burger is added to the MySQL database as ready to eat and the page is reloaded so the burger is displayed in the appropriate section with a \'Devour It!\' button. If the user clicks this button the devoured state for that burger is updated in the MySQL database and the page is reloaded showing the burger moved to the \'Devoured\' section of the page.',
            organization: 'This application is organized using the Model-View-Controller (MVC) design pattern. An Object Relational Mapper (ORM) is defined with functions to handle the MySQL queries and the model further defines those functions specific to the Eat Da Burger application. The routing is defined in the controller and the functions are called as appropriate, once database data is gathered or altered, the view updates from the Handlebars template using a page reload.',
            technologies: 'HTML, Handlebars, CSS, JavaScript, jQuery, MySQL, Node.js, Express, Heroku',
            npmPackages: 'express, express-handlebars, mysql',
            role: 'Sole developer with functionality requirements provided by UW Coding Bootcamp/Trilogy Education Services. Responsible for website design and creation of custom graphics.',
            githubLink: 'https://github.com/lexi-winstanley/BurgerLog',
            projectLink: 'https://nameless-taiga-35229.herokuapp.com/',
            projectImageSrc: '',
            projectImageAlt: ''
        },
        {
            id: '13',
            imageSrc: 'images/swissFavicon.svg',
            imageAlt: '',
            background: '#b5ca30',
            textColor: '#0F0F0D',
            title: 'Swiss Memory Game',
            path: '/eat-da-burger',
            description: 'Eat Da Burger is a web application deployed with Heroku. On home page load, the user is presented with any existing burgers in the MySQL database, non-devoured burgers in the \'Ready to Eat\' section and devoured burgers in the \'Devoured\' section. There is also a form to allow them to input the name of new burgers they\'d like to eat. Once they hit submit, the new burger is added to the MySQL database as ready to eat and the page is reloaded so the burger is displayed in the appropriate section with a \'Devour It!\' button. If the user clicks this button the devoured state for that burger is updated in the MySQL database and the page is reloaded showing the burger moved to the \'Devoured\' section of the page.',
            organization: 'This application is organized using the Model-View-Controller (MVC) design pattern. An Object Relational Mapper (ORM) is defined with functions to handle the MySQL queries and the model further defines those functions specific to the Eat Da Burger application. The routing is defined in the controller and the functions are called as appropriate, once database data is gathered or altered, the view updates from the Handlebars template using a page reload.',
            technologies: 'HTML, Handlebars, CSS, JavaScript, jQuery, MySQL, Node.js, Express, Heroku',
            npmPackages: 'express, express-handlebars, mysql',
            role: 'Sole developer with functionality requirements provided by UW Coding Bootcamp/Trilogy Education Services. Responsible for website design and creation of custom graphics.',
            githubLink: 'https://github.com/lexi-winstanley/BurgerLog',
            projectLink: 'https://nameless-taiga-35229.herokuapp.com/',
            projectImageSrc: '',
            projectImageAlt: ''
        },
        {
            id: '15',
            imageSrc: 'images/friendFinder.svg',
            imageAlt: 'friend finder icon',
            background: '#680a4d',
            textColor: '#f8f7f7',
            title: 'Friend Finder',
            path: '/eat-da-burger',
            description: 'Eat Da Burger is a web application deployed with Heroku. On home page load, the user is presented with any existing burgers in the MySQL database, non-devoured burgers in the \'Ready to Eat\' section and devoured burgers in the \'Devoured\' section. There is also a form to allow them to input the name of new burgers they\'d like to eat. Once they hit submit, the new burger is added to the MySQL database as ready to eat and the page is reloaded so the burger is displayed in the appropriate section with a \'Devour It!\' button. If the user clicks this button the devoured state for that burger is updated in the MySQL database and the page is reloaded showing the burger moved to the \'Devoured\' section of the page.',
            organization: 'This application is organized using the Model-View-Controller (MVC) design pattern. An Object Relational Mapper (ORM) is defined with functions to handle the MySQL queries and the model further defines those functions specific to the Eat Da Burger application. The routing is defined in the controller and the functions are called as appropriate, once database data is gathered or altered, the view updates from the Handlebars template using a page reload.',
            technologies: 'HTML, Handlebars, CSS, JavaScript, jQuery, MySQL, Node.js, Express, Heroku',
            npmPackages: 'express, express-handlebars, mysql',
            role: 'Sole developer with functionality requirements provided by UW Coding Bootcamp/Trilogy Education Services. Responsible for website design and creation of custom graphics.',
            githubLink: 'https://github.com/lexi-winstanley/BurgerLog',
            projectLink: 'https://nameless-taiga-35229.herokuapp.com/',
            projectImageSrc: '',
            projectImageAlt: ''
        },
        {
            id: '16',
            imageSrc: 'images/threeScoreDev.svg',
            imageAlt: '',
            background: '#cbc5ef',
            textColor: '#0F0F0D',
            title: 'Three Score Development',
            path: '/eat-da-burger',
            description: 'Eat Da Burger is a web application deployed with Heroku. On home page load, the user is presented with any existing burgers in the MySQL database, non-devoured burgers in the \'Ready to Eat\' section and devoured burgers in the \'Devoured\' section. There is also a form to allow them to input the name of new burgers they\'d like to eat. Once they hit submit, the new burger is added to the MySQL database as ready to eat and the page is reloaded so the burger is displayed in the appropriate section with a \'Devour It!\' button. If the user clicks this button the devoured state for that burger is updated in the MySQL database and the page is reloaded showing the burger moved to the \'Devoured\' section of the page.',
            organization: 'This application is organized using the Model-View-Controller (MVC) design pattern. An Object Relational Mapper (ORM) is defined with functions to handle the MySQL queries and the model further defines those functions specific to the Eat Da Burger application. The routing is defined in the controller and the functions are called as appropriate, once database data is gathered or altered, the view updates from the Handlebars template using a page reload.',
            technologies: 'HTML, Handlebars, CSS, JavaScript, jQuery, MySQL, Node.js, Express, Heroku',
            npmPackages: 'express, express-handlebars, mysql',
            role: 'Sole developer with functionality requirements provided by UW Coding Bootcamp/Trilogy Education Services. Responsible for website design and creation of custom graphics.',
            githubLink: 'https://github.com/lexi-winstanley/BurgerLog',
            projectLink: 'https://nameless-taiga-35229.herokuapp.com/',
            projectImageSrc: '',
            projectImageAlt: ''
        },
        {
            id: '17',
            imageSrc: 'images/greenCrystal.svg',
            imageAlt: 'green crystal icon',
            background: '#FC354C',
            textColor: '#f8f7f7',
            title: 'Crystal Counting',
            path: '/eat-da-burger',
            description: 'Eat Da Burger is a web application deployed with Heroku. On home page load, the user is presented with any existing burgers in the MySQL database, non-devoured burgers in the \'Ready to Eat\' section and devoured burgers in the \'Devoured\' section. There is also a form to allow them to input the name of new burgers they\'d like to eat. Once they hit submit, the new burger is added to the MySQL database as ready to eat and the page is reloaded so the burger is displayed in the appropriate section with a \'Devour It!\' button. If the user clicks this button the devoured state for that burger is updated in the MySQL database and the page is reloaded showing the burger moved to the \'Devoured\' section of the page.',
            organization: 'This application is organized using the Model-View-Controller (MVC) design pattern. An Object Relational Mapper (ORM) is defined with functions to handle the MySQL queries and the model further defines those functions specific to the Eat Da Burger application. The routing is defined in the controller and the functions are called as appropriate, once database data is gathered or altered, the view updates from the Handlebars template using a page reload.',
            technologies: 'HTML, Handlebars, CSS, JavaScript, jQuery, MySQL, Node.js, Express, Heroku',
            npmPackages: 'express, express-handlebars, mysql',
            role: 'Sole developer with functionality requirements provided by UW Coding Bootcamp/Trilogy Education Services. Responsible for website design and creation of custom graphics.',
            githubLink: 'https://github.com/lexi-winstanley/BurgerLog',
            projectLink: 'https://nameless-taiga-35229.herokuapp.com/',
            projectImageSrc: '',
            projectImageAlt: ''
        },
        {
            id: '19',
            imageSrc: 'images/bri-spy.svg',
            imageAlt: 'bri-spy icon',
            background: '#FC354C',
            textColor: '#f8f7f7',
            title: 'bri-SPY',
            path: '/eat-da-burger',
            description: 'Eat Da Burger is a web application deployed with Heroku. On home page load, the user is presented with any existing burgers in the MySQL database, non-devoured burgers in the \'Ready to Eat\' section and devoured burgers in the \'Devoured\' section. There is also a form to allow them to input the name of new burgers they\'d like to eat. Once they hit submit, the new burger is added to the MySQL database as ready to eat and the page is reloaded so the burger is displayed in the appropriate section with a \'Devour It!\' button. If the user clicks this button the devoured state for that burger is updated in the MySQL database and the page is reloaded showing the burger moved to the \'Devoured\' section of the page.',
            organization: 'This application is organized using the Model-View-Controller (MVC) design pattern. An Object Relational Mapper (ORM) is defined with functions to handle the MySQL queries and the model further defines those functions specific to the Eat Da Burger application. The routing is defined in the controller and the functions are called as appropriate, once database data is gathered or altered, the view updates from the Handlebars template using a page reload.',
            technologies: 'HTML, Handlebars, CSS, JavaScript, jQuery, MySQL, Node.js, Express, Heroku',
            npmPackages: 'express, express-handlebars, mysql',
            role: 'Sole developer with functionality requirements provided by UW Coding Bootcamp/Trilogy Education Services. Responsible for website design and creation of custom graphics.',
            githubLink: 'https://github.com/lexi-winstanley/BurgerLog',
            projectLink: 'https://nameless-taiga-35229.herokuapp.com/',
            projectImageSrc: '',
            projectImageAlt: ''
        },
        {
            id: '20',
            imageSrc: 'images/chapterToo.svg',
            imageAlt: '',
            background: '#041232',
            textColor: '#f8f7f7',
            title: 'Chapter Too Travel Blog',
            path: '/eat-da-burger',
            description: 'Eat Da Burger is a web application deployed with Heroku. On home page load, the user is presented with any existing burgers in the MySQL database, non-devoured burgers in the \'Ready to Eat\' section and devoured burgers in the \'Devoured\' section. There is also a form to allow them to input the name of new burgers they\'d like to eat. Once they hit submit, the new burger is added to the MySQL database as ready to eat and the page is reloaded so the burger is displayed in the appropriate section with a \'Devour It!\' button. If the user clicks this button the devoured state for that burger is updated in the MySQL database and the page is reloaded showing the burger moved to the \'Devoured\' section of the page.',
            organization: 'This application is organized using the Model-View-Controller (MVC) design pattern. An Object Relational Mapper (ORM) is defined with functions to handle the MySQL queries and the model further defines those functions specific to the Eat Da Burger application. The routing is defined in the controller and the functions are called as appropriate, once database data is gathered or altered, the view updates from the Handlebars template using a page reload.',
            technologies: 'HTML, Handlebars, CSS, JavaScript, jQuery, MySQL, Node.js, Express, Heroku',
            npmPackages: 'express, express-handlebars, mysql',
            role: 'Sole developer with functionality requirements provided by UW Coding Bootcamp/Trilogy Education Services. Responsible for website design and creation of custom graphics.',
            githubLink: 'https://github.com/lexi-winstanley/BurgerLog',
            projectLink: 'https://nameless-taiga-35229.herokuapp.com/',
            projectImageSrc: '',
            projectImageAlt: ''
        },
        {
            id: '22',
            imageSrc: 'images/train.svg',
            imageAlt: '',
            background: '#cbc5ef',
            textColor: '#0F0F0D',
            title: 'Train Schedule',
            path: '/eat-da-burger',
            description: 'Eat Da Burger is a web application deployed with Heroku. On home page load, the user is presented with any existing burgers in the MySQL database, non-devoured burgers in the \'Ready to Eat\' section and devoured burgers in the \'Devoured\' section. There is also a form to allow them to input the name of new burgers they\'d like to eat. Once they hit submit, the new burger is added to the MySQL database as ready to eat and the page is reloaded so the burger is displayed in the appropriate section with a \'Devour It!\' button. If the user clicks this button the devoured state for that burger is updated in the MySQL database and the page is reloaded showing the burger moved to the \'Devoured\' section of the page.',
            organization: 'This application is organized using the Model-View-Controller (MVC) design pattern. An Object Relational Mapper (ORM) is defined with functions to handle the MySQL queries and the model further defines those functions specific to the Eat Da Burger application. The routing is defined in the controller and the functions are called as appropriate, once database data is gathered or altered, the view updates from the Handlebars template using a page reload.',
            technologies: 'HTML, Handlebars, CSS, JavaScript, jQuery, MySQL, Node.js, Express, Heroku',
            npmPackages: 'express, express-handlebars, mysql',
            role: 'Sole developer with functionality requirements provided by UW Coding Bootcamp/Trilogy Education Services. Responsible for website design and creation of custom graphics.',
            githubLink: 'https://github.com/lexi-winstanley/BurgerLog',
            projectLink: 'https://nameless-taiga-35229.herokuapp.com/',
            projectImageSrc: '',
            projectImageAlt: ''
        },
        {
            id: '23',
            imageSrc: 'images/somethingBorrowed.svg',
            imageAlt: '',
            background: '#45bce5',
            textColor: '#f8f7f7',
            title: 'Something Borrowed',
            path: '/eat-da-burger',
            description: 'Eat Da Burger is a web application deployed with Heroku. On home page load, the user is presented with any existing burgers in the MySQL database, non-devoured burgers in the \'Ready to Eat\' section and devoured burgers in the \'Devoured\' section. There is also a form to allow them to input the name of new burgers they\'d like to eat. Once they hit submit, the new burger is added to the MySQL database as ready to eat and the page is reloaded so the burger is displayed in the appropriate section with a \'Devour It!\' button. If the user clicks this button the devoured state for that burger is updated in the MySQL database and the page is reloaded showing the burger moved to the \'Devoured\' section of the page.',
            organization: 'This application is organized using the Model-View-Controller (MVC) design pattern. An Object Relational Mapper (ORM) is defined with functions to handle the MySQL queries and the model further defines those functions specific to the Eat Da Burger application. The routing is defined in the controller and the functions are called as appropriate, once database data is gathered or altered, the view updates from the Handlebars template using a page reload.',
            technologies: 'HTML, Handlebars, CSS, JavaScript, jQuery, MySQL, Node.js, Express, Heroku',
            npmPackages: 'express, express-handlebars, mysql',
            role: 'Sole developer with functionality requirements provided by UW Coding Bootcamp/Trilogy Education Services. Responsible for website design and creation of custom graphics.',
            githubLink: 'https://github.com/lexi-winstanley/BurgerLog',
            projectLink: 'https://nameless-taiga-35229.herokuapp.com/',
            projectImageSrc: '',
            projectImageAlt: ''
        },
        {
            id: '24',
            imageSrc: 'images/threeScoreRub.svg',
            imageAlt: '',
            background: '#0072bb',
            textColor: '#f8f7f7',
            title: 'Three Score Rub',
            path: '/eat-da-burger',
            description: 'Eat Da Burger is a web application deployed with Heroku. On home page load, the user is presented with any existing burgers in the MySQL database, non-devoured burgers in the \'Ready to Eat\' section and devoured burgers in the \'Devoured\' section. There is also a form to allow them to input the name of new burgers they\'d like to eat. Once they hit submit, the new burger is added to the MySQL database as ready to eat and the page is reloaded so the burger is displayed in the appropriate section with a \'Devour It!\' button. If the user clicks this button the devoured state for that burger is updated in the MySQL database and the page is reloaded showing the burger moved to the \'Devoured\' section of the page.',
            organization: 'This application is organized using the Model-View-Controller (MVC) design pattern. An Object Relational Mapper (ORM) is defined with functions to handle the MySQL queries and the model further defines those functions specific to the Eat Da Burger application. The routing is defined in the controller and the functions are called as appropriate, once database data is gathered or altered, the view updates from the Handlebars template using a page reload.',
            technologies: 'HTML, Handlebars, CSS, JavaScript, jQuery, MySQL, Node.js, Express, Heroku',
            npmPackages: 'express, express-handlebars, mysql',
            role: 'Sole developer with functionality requirements provided by UW Coding Bootcamp/Trilogy Education Services. Responsible for website design and creation of custom graphics.',
            githubLink: 'https://github.com/lexi-winstanley/BurgerLog',
            projectLink: 'https://nameless-taiga-35229.herokuapp.com/',
            projectImageSrc: '',
            projectImageAlt: ''
        },
        {
            id: '26',
            imageSrc: 'images/sawblade.svg',
            imageAlt: 'saw blade icon',
            background: '#0cb2ba',
            textColor: '#f8f7f7',
            title: 'Woodworking Trivia',
            path: '/eat-da-burger',
            description: 'Eat Da Burger is a web application deployed with Heroku. On home page load, the user is presented with any existing burgers in the MySQL database, non-devoured burgers in the \'Ready to Eat\' section and devoured burgers in the \'Devoured\' section. There is also a form to allow them to input the name of new burgers they\'d like to eat. Once they hit submit, the new burger is added to the MySQL database as ready to eat and the page is reloaded so the burger is displayed in the appropriate section with a \'Devour It!\' button. If the user clicks this button the devoured state for that burger is updated in the MySQL database and the page is reloaded showing the burger moved to the \'Devoured\' section of the page.',
            organization: 'This application is organized using the Model-View-Controller (MVC) design pattern. An Object Relational Mapper (ORM) is defined with functions to handle the MySQL queries and the model further defines those functions specific to the Eat Da Burger application. The routing is defined in the controller and the functions are called as appropriate, once database data is gathered or altered, the view updates from the Handlebars template using a page reload.',
            technologies: 'HTML, Handlebars, CSS, JavaScript, jQuery, MySQL, Node.js, Express, Heroku',
            npmPackages: 'express, express-handlebars, mysql',
            role: 'Sole developer with functionality requirements provided by UW Coding Bootcamp/Trilogy Education Services. Responsible for website design and creation of custom graphics.',
            githubLink: 'https://github.com/lexi-winstanley/BurgerLog',
            projectLink: 'https://nameless-taiga-35229.herokuapp.com/',
            projectImageSrc: '',
            projectImageAlt: ''
        },
        {
            id: '27',
            imageSrc: 'images/crystalBall.svg',
            imageAlt: 'crystal ball icon',
            background: '#680a4d',
            textColor: '#f8f7f7',
            title: 'Letter Guessing Game',
            path: '/eat-da-burger',
            description: 'Eat Da Burger is a web application deployed with Heroku. On home page load, the user is presented with any existing burgers in the MySQL database, non-devoured burgers in the \'Ready to Eat\' section and devoured burgers in the \'Devoured\' section. There is also a form to allow them to input the name of new burgers they\'d like to eat. Once they hit submit, the new burger is added to the MySQL database as ready to eat and the page is reloaded so the burger is displayed in the appropriate section with a \'Devour It!\' button. If the user clicks this button the devoured state for that burger is updated in the MySQL database and the page is reloaded showing the burger moved to the \'Devoured\' section of the page.',
            organization: 'This application is organized using the Model-View-Controller (MVC) design pattern. An Object Relational Mapper (ORM) is defined with functions to handle the MySQL queries and the model further defines those functions specific to the Eat Da Burger application. The routing is defined in the controller and the functions are called as appropriate, once database data is gathered or altered, the view updates from the Handlebars template using a page reload.',
            technologies: 'HTML, Handlebars, CSS, JavaScript, jQuery, MySQL, Node.js, Express, Heroku',
            npmPackages: 'express, express-handlebars, mysql',
            role: 'Sole developer with functionality requirements provided by UW Coding Bootcamp/Trilogy Education Services. Responsible for website design and creation of custom graphics.',
            githubLink: 'https://github.com/lexi-winstanley/BurgerLog',
            projectLink: 'https://nameless-taiga-35229.herokuapp.com/',
            projectImageSrc: '',
            projectImageAlt: ''
        }
    ]
}